apiVersion: v1

kind: Service

metadata:
  labels:
    io.reminder.service: reminder
  name: reminder

spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.reminder.service: reminder

status:
  loadBalancer: {}
