apiVersion: networking.k8s.io/v1

kind: NetworkPolicy

metadata:
  name: postgres-network

spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.reminder.network/postgres-network: "true"
  podSelector:
    matchLabels:
      io.reminder.network/postgres-network: "true"
