apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  labels:
    io.reminder.service: postgres-data
  name: postgres-data

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

status: {}
