apiVersion: apps/v1

kind: Deployment

metadata:
  labels:
    io.reminder.service: postgres
  name: postgres

spec:
  replicas: 1
  selector:
    matchLabels:
      io.reminder.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.reminder.network/postgres-network: "true"
        io.reminder.service: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: reminder
            - name: POSTGRES_USER
              value: reminder
          image: postgres:16-alpine
          name: postgres
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data

status: {}
